### ISSUE TITLE
Custom event editable

### ISSUE THREAD

**Issue by Thothore** [SnaKyEyeS/ADE-Scheduler#141] opened 2020-10-14 16:32 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes when I create a custom event, I didn't input correctly the date and would like to edit it rather than delete and redo

**Describe the solution you'd like**
An edit button next to Delete

**Describe alternatives you've considered**

**Additional context**

**Comment by SnaKyEyeS** [comment] 2020-10-14 16:36
Duplicate of #134

**Closed** 2020-10-14 16:36 UTC
